name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 15分でタイムアウト
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm run build
      
      - name: Prepare deployment (Standalone mode)
        run: |
          mkdir -p deploy
          
          # Next.js standalone build をコピー
          cp -r .next/standalone/. deploy/
          
          # public と static をコピー
          mkdir -p deploy/public
          cp -r public/. deploy/public/
          
          mkdir -p deploy/.next/static
          cp -r .next/static/. deploy/.next/static/
          
          # package.json をコピー（依存関係情報のため）
          cp package.json deploy/
          
      - name: Create startup script
        run: |
          cat > deploy/startup.sh << 'EOF'
          #!/bin/sh
          cd /home/site/wwwroot
          node server.js
          EOF
          chmod +x deploy/startup.sh
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima42'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy
